### ISSUE TITLE
the app crash

### ISSUE THREAD

**Issue by mq3616** [bither/bither-ios#20]
The App crash when I run it on my iPhone, the analysis log info is attached as the picture shows, May you told me why I can't run it successfully?
![image](https://cloud.githubusercontent.com/assets/7642931/7808241/64ba5172-03c4-11e5-9d80-cf744f008bd7.png)

**Comment by songchenwen** [comment]
There is an `app group` Bither uses to communicate with the Apple Watch app. Your error shows that you don't have the entitlements for the `app group`. 

The `app group` name is defined in `GroupFileUtil.h` and also some `info.plist` files. 

You may check the difference between the `enterprise` branch and the `develop` branch to see where do you need to edit to change the `app group` name.

**Comment by songchenwen** [comment]
Closed due to inactivity.
