### ISSUE TITLE
Bitcoin Cash Support for HD-Account?

### ISSUE THREAD

**Issue by Hendrik44** [bither/bither-ios#28]
Does the bither App supports the new Bitcoin Cash? If not, how i can get access to it using an HD Account? Is there an option to export private keys from HD-Account?

**Comment by bithernet** [comment]
We have another product bitpie.com supports Bcash (you can use bitpie wallet for Bcash).

Also the new version of Bither (v1.7.0) supports getting Bcash, and you do not need to export private keys.
