### ISSUE TITLE
Bither doesn´t accept my password

### ISSUE THREAD

**Issue by Thomas0000001** [bither/bither-ios#31]
Hi, I didn´t forget my password but when I want to transfer Bitcoin Bither says "wrong password". I can use the password when opening "Export" e.g. but when I want to transfer it says worng password. What can I do? I am 100% sure it is my password especially it works at other situations.

**Comment by bithernet** [comment]
Do you have any special characters in your password?

**Comment by Thomas0000001** [comment]
yes Have !"§$ in my character. 

    bithernet <notifications@github.com> schrieb am 6:44 Donnerstag, 24.August 2017:
 

 Do you have any special characters in your password?—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.  

   
 
|  | Virenfrei. www.avast.com  |

**Comment by songchenwen** [comment]
@Thomas0000001  If you are using the desktop client, you can update to the latest version and change your password.
