### ISSUE TITLE
i need to restore my wallet how can i do that 

### ISSUE THREAD

**Issue by almoharebh** [bither/bither-ios#32]
i need restore my wallet i have found on wallet

**Comment by bithernet** [comment]
We need more details about your issue.

**Comment by almoharebh** [comment]
like what

**Comment by bithd** [comment]
Like the full description about "what is your issue? and what do you want to do?"

**Comment by bithernet** [comment]
Like the full description about "what is your issue? and what do you want to do?"

**Comment by almoharebh** [comment]
i have my wallet address bither i install it in my ipad when i restore my ipad i lose't bither wallet and the bitcoin inside

**Comment by bithernet** [comment]
Do you have backups? If no, then sorry.
