### ISSUE TITLE
比太钱包获取BTG用冷钱包签名交易时退出！

### ISSUE THREAD

**Issue by dujbo** [bither/bither-ios#34]
热钱包是ANDROID手机，冷钱包是IOS。获取BTG时，用冷钱包签名BTG发送交易时，扫描完成后直接退出，无任何提示！原以为需要升级冷钱包，把冷钱包里的面私钥全部作废，删除冷钱包，然后联网重新安装冷钱包，又重新逐笔导入新的私钥，他妈的折腾了一个小时。重新在热钱包获取BTG，冷钱包扫描完交易后还是直接退出！！！------------------------------------------------------------------------------
比太包钱包究竟在搞什么？！难道不知道用户用你的钱包很大程度上是看中冷、热存储功能吗？连一个领取BTG的功能都做不完善，还让用户怎么放心用！而且最可气的是发送BTG地址只能发到比特派钱包地址，强迫用户使用比特派钱包，增加用户的转账成本，我看你们也是快了！反正我以后是不会用了，去你妈的！
--

**Comment by zhenHH** [comment]
冷钱包请使用安卓手机最新版获取BTG




发自网易邮箱大师
在2017年11月26日 13:52，dujbo 写道：
热钱包是ANDROID手机，冷钱包是IOS。获取BTG时，用冷钱包签名BTG发送交易时，扫描完成后直接退出，无任何提示！原以为需要升级冷钱包，把冷钱包里的面私钥全部作废，删除冷钱包，然后联网重新安装冷钱包，又重新逐笔导入新的私钥，他妈的折腾了一个小时。重新在热钱包获取BTG，冷钱包扫描完交易后还是直接退出！！！------------------------------------------------------------------------------
比太包钱包究竟在搞什么？！难道不知道用户用你的钱包很大程度上是看中冷、热存储功能吗？连一个领取BTG的功能都做不完善，还让用户怎么放心用！而且最可气的是发送BTG地址只能发到比特派钱包地址，强迫用户使用比特派钱包，增加用户的转账成本，我看你们也是快了！反正我以后是不会用了，去你妈的！

**Comment by zhenHH** [comment]
@dujbo 如果您着急获取，建议您冷钱包使用安卓版比太获取，iOS 版本稍等下正在审核中，版本1.7.7可以获取。

**Comment by zhenHH** [comment]
@dujbo 如果您是从官网下载的比太，现在可以更新下获取BTG了，App Store正在审核需要稍等下。
