### ISSUE TITLE
Bither ios recovering system

### ISSUE THREAD

**Issue by foldandfold** [bither/bither-ios#52]
We normal people forget our 1000 different passwords. I want my bitcoins!!

**Comment by songchenwen** [comment]
Your password is to encrypt your private keys. We can't restore your password. If we have means to restore your password, we can have access to your private keys, which means we can potentially spend your bitcoins. 

The word `Decentralization` people always refer to when talking about Bitcoin has a layer of meaning that's self-banking. You will be your own bank, and you will have to remember your own password. I'm sorry no one can do that for you.

I suggest you try your usual passwords with the `check private keys` function. There is no lock out timers, and you can try as many passwords as you want. Hopefully, you will recall your correct password.

If you have any further questions, you can contact our support email support@bither.net

**Comment by foldandfold** [comment]
Your proud?

ma 14.10.2019 klo 4.36 宋辰文 <notifications@github.com> kirjoitti:

**Comment by foldandfold** [comment]
fcking scumpbag


ma 14. lokak. 2019 klo 7.51 nico matukka (nicomatukka@gmail.com) kirjoitti:
