### ISSUE TITLE
关于苹果最新版1.9.3的问题

### ISSUE THREAD

**Issue by 2923857779** [bither/bither-ios#57]
1.从苹果商店下载安装后，没有冷钱包的选项，无法进入冷钱包模式。
2.代码未上传至Github？

**Comment by songchenwen** [comment]
iOS 设备并不推荐作为冷钱包使用，因为 iOS 设备上安装的应用需要定期联网检查证书，否则应用会无法启动，要联网那也就失去了作为冷设备的安全性了。所以推荐还是拿一台安卓手机来作为冷钱包吧。
