### ISSUE TITLE
IOS新版的是不是没办法创建冷钱包了？

### ISSUE THREAD

**Issue by buzhidaocommon** [bither/bither-ios#60]
IOS新版的是不是没办法创建冷钱包了？

**Comment by songchenwen** [comment]
是的，因为iOS的APP需要定期联网跟苹果服务器验证证书，不适合作为冷钱包

**Comment by buzhidaocommon** [comment]
那我需要创建冷钱包只能用安卓？

**Comment by buzhidaocommon** [comment]
> 是的，因为iOS的APP需要定期联网跟苹果服务器验证证书，不适合作为冷钱包

那我要创建冷钱包只能用安卓咯？

**Comment by songchenwen** [comment]
嗯，建议冷钱包还是用安卓设备

**Comment by buzhidaocommon** [comment]
> 嗯，建议冷钱包还是用安卓设备

好的。谢谢
