### ISSUE TITLE
ios14.3 无法进入冷钱包模式，在线等，挺急的。

### ISSUE THREAD

**Issue by lurengeng** [bither/bither-ios#62]
已经多次实验：卸载比太（卸载/删除app），重新安装，关闭网络，打开飞行模式（手机里也没插卡），重新打开比太钱包。

在选择冷热钱包的地方一闪而过，不给我选择的机会。然后就进入了热钱包模式。
热钱包模式下面，进入设置，也没有网上经常出现的“切换至冷钱包“的选项。

iPhone7  , iOS 14.3  好像不能降级了。
在线等，挺急的。

**Comment by songchenwen** [comment]
ios版本已经取消了对冷钱包模式的支持，因为苹果会定期联网检查安装应用的证书，如果长时间无法联网会导致应用无法启动。这样对用户来说就并不适合拿来做冷钱包了。我们还是建议用安卓设备做冷钱包。

**Comment by lurengeng** [comment]
> ios版本已经取消了对冷钱包模式的支持，因为苹果会定期联网检查安装应用的证书，如果长时间无法联网会导致应用无法启动。这样对用户来说就并不适合拿来做冷钱包了。我们还是建议用安卓设备做冷钱包。

@songchenwen iOS和比太哪个版本还可以用冷钱包？我这是彻底回不去了嘛？我的小伙伴都在用啊。
我听说iOS安全稳定，才特意买了个iPhone 当冷钱包用（手里好几个安卓二手机，但是怕铁拳没敢用）
还有没有办法呢？
